resolve #16 投稿内容を保存するAPI
jphacks/D_2202 pull request #18
Opened 2022-10-18 17:17 UTC by asamakei

投稿内容(植物名, 緯度, 経度, 画像データ, タグ名のリスト)をPOST(JSON)で受け取りデータベースに保存するAPI。
同じ名前の植物が存在しない場合は新たにplantに追加。
タグを1個以上指定した場合は投稿した植物にそのタグを追加。

画像データはbase64の文字列で受け取ってfigureフォルダに保存してるけど、gcsにFlutterから直でアップロードするので後々消す。代わりにそのurlかhashを受け取るようにする。

思ったより盛りだくさんだったのでIssueを分けるべきだった。

2022-10-18 18:43 UTC, moririn2528 commented
この /post , POST 送信って意味じゃなくて、投稿の post なのか…

2022-10-18 18:50 UTC, moririn2528 commented
/post/upload にした方がいいかな…
で、なまえも Post から UploadPost とかにしてほしい、それなら post 送信との区別がつきそう

2022-10-18 19:36 UTC, moririn2528 requested changes
これらの変更と、前述の命名の変更を全体的にしてほしい！

2022-10-18 19:36 UTC, moririn2528 commented on go/README.md
> +- isnew 1なら植物データを新しく登録 0なら既に存在
戻り値の isnew、さすがに boolean にしてほしい
~キー、"is_new" の方が見やすそうだけどどうだろう~
is_new は投稿が新しいのか植物が新しいのかわからないので、植物だったら is_new_plant とかわかりやすくしてほしい

2022-10-18 19:36 UTC, moririn2528 commented on go/README.md
> +- newid 新しく登録した際のid(これ要る？)
この後に絶対 id がいる API でもなさそうだし、その場合は id が必要だったら GET API 読んでくださいスタイルでよさそうなので、いらないかな

2022-10-18 19:36 UTC, moririn2528 commented on go/communicate/post.go
> +	//"encoding/base64"
細かいけど、消しといて

2022-10-18 19:36 UTC, moririn2528 commented on go/communicate/post.go
> +	//"encoding/base64"
//"os" も同様

2022-10-18 19:36 UTC, moririn2528 commented on go/communicate/post.go
> +type PostResult struct {
まず、API の入力は Request(s) 出力は Response(s)
そして、この場所に書かれた PostResult は communicate パッケージ内の任意のファイルから呼び出せるので名前は変えたい

2022-10-18 19:36 UTC, moririn2528 commented on go/communicate/post.go
> +	str += t_str
t := time.Now()
layout := "20060102150405"
t_str := t.Format(layout)
で可能

2022-10-18 19:36 UTC, moririn2528 commented on go/communicate/post.go
> +	str += t_str
この関数は usecase 層に書くべき

2022-10-18 19:36 UTC, moririn2528 commented on go/database/post.go
> +	query := "INSERT INTO post(plant_id, latitude, longitude, hash) VALUES ("
https://github.com/jmoiron/sqlx
ここの README.md のように db.NamedExec を使ってください
query := "INSERT INTO post(hoge,huga) VALUES (:hoge, ;huga)" とかにして、クエリ文に直接データを書き込まないようにすると、変なエラー起きにくく、セキュリティ面でもよいのでお願いします。

2022-10-18 19:36 UTC, moririn2528 commented on go/database/plant.go
> +	newId, err := GetNewPlantID()
AUTOINCREMENT にして GetNewPlantID 関数なくした方がよさそう

2022-10-18 19:36 UTC, moririn2528 commented on go/database/plant.go
> +	plant.Id = newId
同様に NamedExec で

2022-10-18 19:36 UTC, moririn2528 commented on go/database/plant.go
> +	}
```suggestion
	quote_names = []
	for i, t := range tagNames {
		quote_names.append(strconv.Quote(t))
	}
	query_main += "SELECT * FROM tag WHERE name IN ("+strings.Join(quote_names,",")+")"
```
とかの方が見やすい気がする。

2022-10-18 19:36 UTC, moririn2528 commented on go/communicate/post.go
> +	}
このあたりの処理は communicate 層でやるべきでない
usecase 層に書く

2022-10-18 23:06 UTC, asamakei commented on go/communicate/post.go
> +type PostResult struct {
他のファイルから呼び出すこともなさそうなので定義をinsertUploadPostの中に移動
名前は一応UploadPostResponseに変更

2022-10-19 00:43 UTC, asamakei commented on go/database/plant.go
> +	newId, err := GetNewPlantID()
AUTOINCREMENTに変更。
新しく挿入した植物のidが必要だったから、挿入後にlast_insert_rowid()を使って取得した。

2022-10-19 02:33 UTC, asamakei commented
指摘してもらったところを一通り修正した
動作確認はしたのでとりあえずはちゃんと動く

2022-10-19 03:55 UTC, moririn2528 approved these changes
よさそう！

2022-10-19 03:56 UTC, merged